version: '2'

services:
    mysql:
        image: mysql
        restart: always
        environment:
           - variables.env
        # volumes:
        #     - ./data/mysql:/docker-entrypoint-initdb.d
    nginx:
        depends_on:
            - phpfpm
        image: nginx
        ports:
            - "80:80"
        restart: always
        working_dir: /var/www
        volumes:
            - ./wordpress:/var/www/
            - ./conf/nginx/vance.conf:/etc/nginx/conf.d/default.conf
        links:
            - phpfpm
    
    phpfpm:
        image: phalconphp/php-apache:ubuntu-16.04
        restart: always
        working_dir: /var/www
        ports:
            - "8080:80"
        volumes:
            - ./wordpress:/var/www
        depends_on:
            - mysql
    download: 

        image: nginx
        restart: 'no'
        volumes:
            - ./:/var/www
        command: sh download-wp.sh

   

